agents_codename = input("What is your codename?  ")
agents_real_name = input("What is your real name?  ")
assigned_gadjet = input("What is your assigned gadjet?  ")
mission_location = input("Where is your mission location?  ")
operation_number = input("What is your operation number?  ")

print(f"{'='*40}")
print("      TOP SECRET - AGENT DOSSIER")
print(f"{'='*40}")
print(f"{''*40}")
print(f"Codename:   {agents_codename}")
print(f"Real Name:  {agents_real_name}")
print(f"Gadjet:     {assigned_gadjet}")
print(f"{''*40}")
print(f"{'-'*40}")
print(f"MISSION DETAILS:")
print(f"Operation ID:   OP-{operation_number}-{agents_codename}")
print(f"Location:       {mission_location}")
print(f"{'-'*40}")
print(f"       {'*'*3} FOR YOUR EYES ONLY  {'*'*3}")
print(f"{'='*40}")
